import "./globals.css";
import Home from "./components/home/home";

export const metadata = {
  title: "Travel Blog",
  description: "Generated by create next app",
};

export default function App() {
  return <Home />;
}
